services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crave_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  fast-api:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env  # ✅ This ensures FastAPI loads all API keys
    volumes:
      - .:/app  # Optional: to sync code changes for local dev

volumes:
  pgdata:
