services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crave_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]  # Use CMD-SHELL
      interval: 5s
      retries: 5
      start_period: 10s

  fast-api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
    #command: ["/bin/bash", "/app/entrypoint.sh"] # This can help locally, but is usually not needed *if* Dockerfile is correct.

volumes:
  pgdata: