[environments.production]
https_only = true

[environments.production.build]
builder = "dockerfile"

[environments.production.deploy]
startCommand = "./entrypoint.sh"
healthcheckPath = "/api/health/"
healthcheckTimeout = 30

[deploy]
numReplicas = 1
healthcheckPath = "/api/health/"
healthcheckTimeout = 30

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"