"""
Fix users.id autoincrement behavior with proper starting value

Revision ID: 20250228_fix_users_id
Revises: 20250227_add_user_columns
Create Date: 2025-02-28 12:00:00.000000
"""
from alembic import op
import sqlalchemy as sa

revision = "20250228_fix_users_id"
down_revision = "20250227_add_user_columns"
branch_labels = None
depends_on = None

def upgrade() -> None:
    op.execute("ALTER TABLE users ALTER COLUMN id DROP DEFAULT")
    op.execute("ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (START WITH 2)")

def downgrade() -> None:
    op.execute("ALTER TABLE users ALTER COLUMN id DROP IDENTITY IF EXISTS")